### PR TITLE
feat: Handle rate limiting, refactor main.py

### PR DESCRIPTION
**Pull request by DjordyKoert**
This PR will add:

- Handling for rate limit during login
- Exceptions can now be found inside their own directory `Exceptions/`
- Refactor `main.py`:
  - Prevent file from being imported inside 
  - Seperate initialization & main program logic (`init()` & `main()` methods)
  - Move logic for exception handling (`KeyboardInterrupt`, `SystemExit`, `CapsuleFarmerEvolvedException`)

### CODE REVIEW

**Comment by bblxssm** [comment]
LGTM. Good PR

**Comment by auroraisluna** [comment]
Nice. I like the exceptions folder. Should merge this before working on #43 so there isn't conflicts.

**Comment by TheFeelTrain** [comment]
I tried running this branch to see if it helps with https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/issues/50 but had the same problem as before. Looks like it did catch the 403 a few times but still eventually exited. Ran in debug mode this time.

[capsulefarmer-2023-02-04.log](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10609925/capsulefarmer-2023-02-04.log)

**Comment by DjordyKoert** [comment]
> I tried running this branch to see if it helps with #50 but had the same problem as before. Looks like it did catch the 403 a few times but still eventually exited. Ran in debug mode this time.
> 
> [capsulefarmer-2023-02-04.log](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10609925/capsulefarmer-2023-02-04.log)

This PR will not help with that issue. It handles rate limits (code 429). The issue u mentioned is a problen with code 403 and has to be fixed in a different PR.

**Comment by TheFeelTrain** [comment]
Ohh alright. I guess that's why you deleted your comment. I just saw it from the email notification so I thought it was worth a shot.

**Comment by LeagueOfPoro** [comment]
Looks good, nice PR. Merging.

**Pull request merged**
