### PR TITLE
feat: PEP8 Code Styling adjustments

### PR DESCRIPTION
**Pull request by hypixus**
Adjusted entire codebase to fit (as much as possible) with the PEP 8 Style Guide directives, fixed issue with improper type handling for log initiating, updated .gitignore to not send `.idea` directory containing local environment data.

### CODE REVIEW

**Comment by hypixus** [comment]
Please thoroughly review the changes before merging. The names were adjusted across nearly entire project - I did test them locally and nothing broke, but my testing only spans regular flow.

**Comment by auroraisluna** [comment]
I personally dislike anything but camelCase for variables etc. But that is my own personal likes/dislikes. Would need a comment from @LeagueOfPoro for this. 

Also, can you move https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/63/commits/2e1150c75036c00b66db9910c68fba6f4177d2be to a different PR? The PEP 8 adjustment it a 'major' break it self and should be merged and reviewed alone 😃

**Comment by hypixus** [comment]
> I personally dislike anything but camelCase for variables etc. But that is my own personal likes/dislikes. Would need a comment from @LeagueOfPoro for this.
> 
> Also, can you move [2e1150c](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/commit/2e1150c75036c00b66db9910c68fba6f4177d2be) to a different PR? The PEP 8 adjustment it a 'major' break it self and should be merged and reviewed alone 😃 I have marked your PR as draft, please un-draft when that commit is removed, so I can also run actions.

The aforementioned addition of parameters is one of results of fixing of the types used to manage creating logging. Before this PR `Logging` class created an instance of itself with initializing logs for no reason. I can adjust the PR to not have those fixes, however that would return the mess with types. See the screenshot below:
image

**Comment by hypixus** [comment]
> I personally dislike anything but camelCase for variables etc. But that is my own personal likes/dislikes. Would need a comment from @LeagueOfPoro for this.

I come from C# development and trust me, it hurts me just as much - however keeping the code clean will result in better capability of other parties participating in development of this tool.

**Comment by auroraisluna** [comment]
> > Also, can you move [2e1150c](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/commit/2e1150c75036c00b66db9910c68fba6f4177d2be) to a different PR? The PEP 8 adjustment it a 'major' break it self and should be merged and reviewed alone 😃 I have marked your PR as draft, please un-draft when that commit is removed, so I can also run actions.
> 
> The aforementioned addition of parameters is one of results of fixing of the types used to manage creating logging. Before this PR `Logging` class created an instance of itself with initializing logs for no reason. I can adjust the PR to not have those fixes, however that would return the mess with types. See the screenshot below: image

I understand, but its better to have it split, mostly because so we can merge that particular fix alone!

**Comment by hypixus** [comment]
@auroraisluna Revert complete. I could not do it via regular revert as I contained it entirely within main commit, but the 6a38a91 and 540e6b1 should suffice.

**Review by auroraisluna — APPROVED** [review]
LGTM.

**Comment by LeagueOfPoro** [comment]
Honestly, camelCase all the way for me to. The PEP is just wrong.

**Pull request closed without merging**
