### PR TITLE
feat: Add Location Geocode & Area to requests

### LINKED ISSUE #152: [Suggestion]: Add Location Geocode/Area to Config
### What is your idea?

Currently the Location Geocode/Area that is being sent to Riot is "CZ".
I think it would be beneficial to have the ability for customization in the `config.yaml`.

[Location-01](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/blob/93cd8b2bf0a895b9f3b516a71f33eb7a07275769/src/Browser.py#L188)

### What should happen?

Add a option to the `config.yaml` containing a geocode/area. 
If not provided or invalid use a predefined geocode/area.

### My request is not a question

- [x] I acknowledge that this issue is not a question or a bug request.

### PR DESCRIPTION
**Pull request by wneel**
Fixes #152

## Summary of Changes

I added a function that GETs the user's location via an endpoint on lolesports.com.

To do so I added the import of 2 libraries:
re, which allows parsing strings into REGEX,
and json, which allows to transform text into a json object

I get the user's location data in a string variable called geoinfo, an example of geoinfo value is `window._geoinfo = {"code": "FR", "area": "EU", "locale": "fr-FR"}`

then I get the content of the JSON object thanks to the REGEX, so my geoinfo_json variable is a json object which could have for value `{"code": "FR", "area": "EU", "locale": "fr-FR"}`,

Then I store them in the geoinfo variable in the self and access them on line 211 during the request that specifies our location

## Additional context

Discord username: Welv'in7#8230

## Testing instructions

You can look for variable values but I checked everything and used a VPN or from anywhere it works well

### Using [GitHub CLI](https://cli.github.com/)
1. Clone this PR
2. Run `gh pr checkout 124` (Requires [GitHub CLI](https://cli.github.com/)) 
3. Follow the [Advanced Installation Guides from the Wiki](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki)

### Using regular GIT
1. Fetch the PR `git fetch origin pull/<PR_NUMBER>/head:<LOCAL_BRANCH_NAME>` (e.g. `git fetch origin pull/110/head:notif`)
2. Checkout the branch `git checkout <LOCAL_BRANCH_NAME>` (e.g. `git checkout notif`)
3. Follow the [Advanced Installation Guides from the Wiki](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki)

### CODE REVIEW

**Comment by Skribb11es** [comment]
Appears to be a relatively pointless change, seeing as there is no reason to change the country code as is. Also, the country code has 0 impacts on how the farmer works at all, it could be totally removed, and the farmer would still have the exact same function as before. If riot does anything with this information it's almost entirely just for statistics, at which point why should we help Riot identify where the farmer's users are actually located? Yes sure we are providing them with our account which has this information, but why add more to the farmer for something that already does nothing?

**Comment by auroraisluna** [comment]
> Appears to be a relatively pointless change, seeing as there is no reason to change the country code as is. Also, the country code has 0 impacts on how the farmer works at all, it could be totally removed, and the farmer would still have the exact same function as before. If riot does anything with this information it's almost entirely just for statistics, at which point why should we help Riot identify where the farmer's users are actually located? Yes sure we are providing them with our account which has this information, but why add more to the farmer for something that already does nothing?

This and also if a user that is advanced enough to know it really only matters for statistics and they REALLY want to show riot their location, they can just compile the program them selfs with the fields edited

**Comment by x-Wawa** [comment]
> Appears to be a relatively pointless change, seeing as there is no reason to change the country code as is. Also, the country code has 0 impacts on how the farmer works at all, it could be totally removed, and the farmer would still have the exact same function as before. If riot does anything with this information it's almost entirely just for statistics, at which point why should we help Riot identify where the farmer's users are actually located? Yes sure we are providing them with our account which has this information, but why add more to the farmer for something that already does nothing?

First of all, just because it works doesn't mean it's good, If we take a look to Riot pinion on botting and automated systems in league we can easily see that they are about to change a lot of things, first they were talking about removing or changing the way we can currently up account levels 30 fully automatically.

> This project comes with no guarantee or warranty. You are responsible for whatever happens from using this project. No bans have been reported from using this project but it is not a guarantee. This is a personal project and is in no way affiliated with Riot Games.
(REAMDE.md)
Then we talk about a program who contain this disclaimer into the reamde, we have in fact no idea for what type of use they collect location or other type of stuff. If tomorrow a moderator would wake up and ban all players who watch match 24h a day from CZ while they leave in USA they could without any justification because this goes against the rules of Riot.

It is our duty to guarantee the maximum possible safety in the use of the program.

**Comment by Skribb11es** [comment]
> If we take a look to Riot pinion on botting and automated systems in league we can easily see that they are [about to change a lot of things](https://twitter.com/RiotK3o/status/1615260431639252993). 

Yes, they are cracking down on botting, however, all the botting issues that they have discussed publicly and or in any other reference by any riot developer, have all been related to in-game botting, and ranked in particular. There is no indication from Riot in any formal or informal manner that botting drops is in any way a bannable offense. Not to mention, botting in the game has been against Riot's TOS for a long time. Whereas what is being accomplished with the farmer has never been part of Riot's TOS. Even if you reference the tweet you directly linked to, this is again regarding botting in-game, not anything external to League. 

>  If tomorrow a moderator would wake up and ban all players who watch match 24h a day from CZ while they leave in USA they could without any justification because this goes against the rules of Riot.

One, that might be potentially the dumbest thing a Riot admin could do. One the high amount of false positives more than outweigh the people that they might potentially be banning for "justified" purposes. Two, the farmer has and most likely never will be against Riot's TOS, making the odds of this happening slim to none. Finally, if Riot does decide to change its TOS, they consistently give a grace period of a few days between TOS changes to make sure that all the users are able to accommodate the changes. 

Yes, it is in our best interest to provide the best safety to the users of the farmer, however as is, there is no need for a change to this section, along with the potentially convoluted addition of config options for something that likely few will ever touch, there is no need for such a change.

**Comment by LeagueOfPoro** [comment]
I also don't believe this change is needed. Closing.

**Comment by wneel** [comment]
And now ?

**Pull request closed without merging**
