### PR TITLE
feat: Created function that gets the unofficial Riot API key from the website.

### PR DESCRIPTION
**Pull request by 14ROVI**
Motivation is that the unofficial Riot API key could change at any moment. With this function we can dynamically grab it without having to worry about updating the source code.

### CODE REVIEW

**Comment by LeagueOfPoro** [comment]
I think the regex is more likely to break than the API key.

**Comment by LeagueOfPoro** [comment]
However, if you want, we can save the api constant in Config class and load it from there. That way, we can easily swap it if they decide to change it.

**Comment by LeagueOfPoro** [comment]
Solves #102

**Comment by 14ROVI** [comment]
Having it as a constant in the Config class would be very good. I'm unsure if it is worth it to have a similar feature like the `bestStreams.txt` and how it is fetched from the github. Maybe we could have a `APIToken.txt` that it fetches?

**Comment by LeagueOfPoro** [comment]
Just a simple constant is fine. I checked old requests and it's been there for at least a year.

**Comment by hypixus** [comment]
I side with the author of pull request, but a constant is enough for now. Maybe let's move that to config file?

**Comment by DjordyKoert** [comment]
Just defining a constant is good enough. Adding it to config will most likely result in people changing it accidentally.

**Comment by auroraisluna** [comment]
By adding to config, I think poro is referring to adding it as a potential variable. The default config file, should **NOT** change at all.

**Comment by LeagueOfPoro** [comment]
> By adding to config, I think poro is referring to adding it as a potential variable. The default config file, should **NOT** change at all.

Exactly this.

**Review by hypixus — CHANGES_REQUESTED** [review]
As mentioned , please change code to simply contain a constant. For now there is no real need for fetching key every session.

**Comment by auroraisluna** [comment]
> As mentioned , please change code to simply contain a constant. For now there is no real need for fetching key every session.
The scope of this PR is to perform the dynamic API key fetching. 

@14ROVI Keep this PR open for the dynamic fetching per session part, since you have already made this functionality. There is no need to revert it or alter it. 

Open a new PR however with the constant one so we can merge it soon.

**Comment by 14ROVI** [comment]
ok uwu.

I dont understand why we shouldnt close this PR now though because it is essentially useless

**Comment by 14ROVI** [comment]
#131

**Pull request closed without merging**
